export interface MobileApp {
  id: string;
  name: string;
  description: string;
  packageId: string;
  iconPath?: string;
  iconName?: string;
  category: string;
  featured?: boolean;
}

export const mobileApps: MobileApp[] = [
  {
    id: 'filmo',
    name: 'FILMO – Film Camera',
    description: 'Capture the beauty and magic of old school vintage images with authentic film textures.',
    packageId: 'com.ssolstice.camera',
    iconPath: '/logo_filmo.webp',
    category: 'Photography',
    featured: true,
  },
  {
    id: 'oldsoul',
    name: 'OldSoul – Film Camera',
    description: 'Classic film camera experience with beautiful retro filters and textures.',
    packageId: 'com.ssolstice.camera.oldsoul',
    iconPath: '/icon_oldsoul.webp',
    category: 'Photography',
    featured: true,
  },
  {
    id: 'manual',
    name: 'Manual 2 – Pro Manual Camera',
    description: 'Simple and effective manual controls for your mobile photography.',
    packageId: 'com.ssolstice.camera.manual',
    iconPath: '/icon_manual.webp',
    category: 'Photography',
    featured: true,
  },
  {
    id: 'dualview',
    name: 'Dual Camera & PiP - DualView',
    description: 'Record from both front and rear cameras simultaneously with Picture-in-Picture mode.',
    packageId: 'com.ssolstice.dualcamera',
    iconPath: '/logo_dualview.webp',
    category: 'Video',
    featured: true,
  },
  {
    id: 'fieldly-gps',
    name: 'Fieldly: GPS Camera, Timestamp',
    description: 'Add location, time, and custom metadata directly to your photos with high precision.',
    packageId: 'com.ssolstice.time',
    iconPath: '/logo_fiedly.png',
    category: 'Utility',
    featured: true,
  },
  {
    id: 'filmory',
    name: 'Filmory – Pro Film Camera',
    description: 'A professional-grade camera app designed for enthusiasts of classic film photography.',
    packageId: 'com.ssolstice.filmory',
    iconPath: '/logo_filmory.webp',
    category: 'Photography',
    featured: true,
  },
  {
    id: 'auraraw',
    name: 'AuraRAW – Pro Manual Camera',
    description: 'Pro-level manual camera app supporting RAW for ultimate photography control.',
    packageId: 'com.s2olstice.auraraw.camera',
    iconPath: '/icon_auraraw.webp',
    category: 'Photography',
    featured: true,
  },
  {
    id: 'everlog',
    name: 'EverLog – Event Timeline Log',
    description: 'Keep a precise log of events and create beautiful timelines for your personal or work life.',
    packageId: 'com.ssolstice.everlog',
    iconPath: '/logo_everlog.webp',
    category: 'Productivity',
    featured: true,
  },
  {
    id: 'privatevault',
    name: 'Private Vault – Hide Photos',
    description: 'Secure your private photos and videos with high-grade encryption and a secret vault.',
    packageId: 'com.ssolstice.vault',
    iconPath: '/logo_privatevault.webp',
    category: 'Security',
    featured: true,
  },
  {
    id: 'photomap',
    name: 'Journiq - Photo map & Journeys',
    description: 'Visualize your journeys and photos on an interactive map.',
    packageId: 'com.ssolstice.journiq',
    iconPath: '/logo_photomap.webp',
    category: 'Travel',
    featured: true,
  },
  {
    id: 'aurapro',
    name: 'AuraPro – Manual Camera',
    description: 'Unlock full manual control over your camera for the perfect shot every time.',
    packageId: 'com.s2olstice.aurapro',
    iconName: 'Sliders',
    category: 'Photography',
  },
  {
    id: 'filshot',
    name: 'FilShot – Film Camera',
    description: 'Quick and easy film photography with a variety of vintage presets.',
    packageId: 'com.ssolstice.vintage.camera.editor',
    iconPath: '/logo_filshot.webp',
    category: 'Photography',
  },
  {
    id: 'laphoto',
    name: 'LA Photo Editor',
    description: 'Comprehensive photo editor with powerful tools and creative filters.',
    packageId: 'com.ssolstice.photoeditor',
    iconPath: '/icon_la_photo.webp',
    category: 'Photography',
  },
  {
    id: 'browser',
    name: '10MB Browser – Fast & Clean',
    description: 'A lightweight, ultra-fast web browser without ads or news feeds for a clean experience.',
    packageId: 'com.ssolstice.browser',
    iconPath: '/logo_browser.webp',
    category: 'Productivity',
  },
  {
    id: 'iptvplayer',
    name: 'IPTV+ Player – Live TV',
    description: 'Stream your M3U playlists with ease. Supports Chromecast and high-quality playback.',
    packageId: 'com.ssolstice.iptv',
    iconPath: '/logo_iptv.webp',
    category: 'Entertainment',
  },
  {
    id: 'fieldly-survey',
    name: 'Fieldly: Survey Camera',
    description: 'Specialized camera for survey and field work with metadata support.',
    packageId: 'com.ssolstice.surveycam',
    iconPath: '/logo_fiedly.png',
    category: 'Utility',
  },
  {
    id: 'cleanium',
    name: 'Cleanium – Phone Cleaner',
    description: 'Optimize your storage by finding and removing junk files and duplicate photos.',
    packageId: 'com.ssolstice.storage.cleanup',
    iconPath: '/logo_cleanium.webp',
    category: 'Utility',
  },
  {
    id: 'fakegps',
    name: 'Fake GPS Location',
    description: 'Simulate or spoof your GPS location with ease for testing or privacy purposes.',
    packageId: 'com.ssolstice.fakegps',
    iconPath: '/logo_fakegps.webp',
    category: 'Utility',
  },
  {
    id: 'noteit',
    name: 'NoteIt – Simple Notes',
    description: 'Quickly jot down your ideas and manage your lists with ease.',
    packageId: 'com.ssolstice.noteit',
    iconPath: '/logo_noteit.webp',
    category: 'Productivity',
  },
];
