import dynamic from 'next/dynamic';
import React from 'react';

const loading = () => <div className="p-8 text-center text-muted-foreground">Loading Tool...</div>;

export const toolRegistry: Record<string, React.ComponentType<any>> = {
  // Developer Tools
  JsonFormatter: dynamic(() => import('./components/JsonFormatter'), { loading, ssr: false }),
  JsonValidator: dynamic(() => import('./components/JsonValidator'), { loading, ssr: false }),
  JsonMinifier: dynamic(() => import('./components/JsonMinifier'), { loading, ssr: false }),
  JsonEscape: dynamic(() => import('./components/JsonEscape'), { loading, ssr: false }),
  JsonUnescape: dynamic(() => import('./components/JsonUnescape'), { loading, ssr: false }),
  JsonCompare: dynamic(() => import('./components/JsonCompare'), { loading, ssr: false }),
  JsonViewer: dynamic(() => import('./components/JsonViewer'), { loading, ssr: false }),
  JsonToYaml: dynamic(() => import('./components/JsonToYaml'), { loading, ssr: false }),
  JsonToXml: dynamic(() => import('./components/JsonToXml'), { loading, ssr: false }),
  JsonToCsv: dynamic(() => import('./components/JsonToCsv'), { loading, ssr: false }),
  CsvToJson: dynamic(() => import('./components/CsvToJson'), { loading, ssr: false }),
  Base64Tool: dynamic(() => import('./components/Base64Tool'), { loading, ssr: false }),
  UrlTool: dynamic(() => import('./components/UrlTool'), { loading, ssr: false }),
  UuidGenerator: dynamic(() => import('./components/UuidGenerator'), { loading, ssr: false }),
  Sha256Generator: dynamic(() => import('./components/Sha256Generator'), { loading, ssr: false }),
  RegexTester: dynamic(() => import('./components/RegexTester'), { loading, ssr: false }),
  TimestampConverter: dynamic(() => import('./components/TimestampConverter'), { loading, ssr: false }),
  HtmlMinifier: dynamic(() => import('./components/HtmlMinifier'), { loading, ssr: false }),
  CssMinifier: dynamic(() => import('./components/CssMinifier'), { loading, ssr: false }),
  JsMinifier: dynamic(() => import('./components/JsMinifier'), { loading, ssr: false }),

  // Text Tools
  WordCounter: dynamic(() => import('./components/WordCounter'), { loading, ssr: false }),
  CaseConverter: dynamic(() => import('./components/CaseConverter'), { loading, ssr: false }),
  SlugGenerator: dynamic(() => import('./components/SlugGenerator'), { loading, ssr: false }),
  SpaceRemover: dynamic(() => import('./components/SpaceRemover'), { loading, ssr: false }),
  TextSorter: dynamic(() => import('./components/TextSorter'), { loading, ssr: false }),
  DuplicateRemover: dynamic(() => import('./components/DuplicateRemover'), { loading, ssr: false }),
  TextReverser: dynamic(() => import('./components/TextReverser'), { loading, ssr: false }),
  CharacterCounter: dynamic(() => import('./components/CharacterCounter'), { loading, ssr: false }),
  RandomTextGenerator: dynamic(() => import('./components/RandomTextGenerator'), { loading, ssr: false }),
  LoremIpsumGenerator: dynamic(() => import('./components/LoremIpsumGenerator'), { loading, ssr: false }),
  DuplicateWordRemover: dynamic(() => import('./components/DuplicateWordRemover'), { loading, ssr: false }),
  FindReplace: dynamic(() => import('./components/FindReplace'), { loading, ssr: false }),
  LineCounter: dynamic(() => import('./components/LineCounter'), { loading, ssr: false }),
  SentenceCounter: dynamic(() => import('./components/SentenceCounter'), { loading, ssr: false }),
  ReadingTime: dynamic(() => import('./components/ReadingTime'), { loading, ssr: false }),
  MarkdownPreview: dynamic(() => import('./components/MarkdownPreview'), { loading, ssr: false }),
  TextCompare: dynamic(() => import('./components/TextCompare'), { loading, ssr: false }),

  // Image Tools
  ImageCompressor: dynamic(() => import('./components/ImageCompressor'), { loading, ssr: false }),
  ConvertToPng: dynamic(() => import('./components/ConvertToPng'), { loading, ssr: false }),
  ConvertToJpg: dynamic(() => import('./components/ConvertToJpg'), { loading, ssr: false }),
  ConvertToWebp: dynamic(() => import('./components/ConvertToWebp'), { loading, ssr: false }),
  ImageResizer: dynamic(() => import('./components/ImageResizer'), { loading, ssr: false }),
  ImageEditor: dynamic(() => import('./components/ImageEditor'), { loading, ssr: false }),
  ImageBase64Tool: dynamic(() => import('./components/ImageBase64Tool'), { loading, ssr: false }),
  ImageMetadataTool: dynamic(() => import('./components/ImageMetadataTool'), { loading, ssr: false }),
  ImageColorTool: dynamic(() => import('./components/ImageColorTool'), { loading, ssr: false }),
  ThumbnailGenerator: dynamic(() => import('./components/ThumbnailGenerator'), { loading, ssr: false }),
  BlurDetector: dynamic(() => import('./components/BlurDetector'), { loading, ssr: false }),
  HeicToJpg: dynamic(() => import('./components/HeicToJpg'), { loading, ssr: false }),
  HeicToPng: dynamic(() => import('./components/HeicToPng'), { loading, ssr: false }),
  SvgToPng: dynamic(() => import('./components/SvgToPng'), { loading, ssr: false }),
  SvgOptimizer: dynamic(() => import('./components/SvgOptimizer'), { loading, ssr: false }),
  IcoGenerator: dynamic(() => import('./components/IcoGenerator'), { loading, ssr: false }),
  FaviconGenerator: dynamic(() => import('./components/FaviconGenerator'), { loading, ssr: false }),
  ImageWatermark: dynamic(() => import('./components/ImageWatermark'), { loading, ssr: false }),
  AspectRatioCalculator: dynamic(() => import('./components/AspectRatioCalculator'), { loading, ssr: false }),
  ImageOcr: dynamic(() => import('./components/ImageOcr'), { loading, ssr: false }),
  ImageCropTool: dynamic(() => import('./components/ImageCropTool'), { loading, ssr: false }),

  // PDF Tools
  PdfMergeTool: dynamic(() => import('./components/PdfMergeTool'), { loading, ssr: false }),
  PdfSplitTool: dynamic(() => import('./components/PdfSplitTool'), { loading, ssr: false }),
  ImageToPdf: dynamic(() => import('./components/ImageToPdf'), { loading, ssr: false }),
  PdfToImage: dynamic(() => import('./components/PdfToImage'), { loading, ssr: false }),
  PdfToText: dynamic(() => import('./components/PdfToText'), { loading, ssr: false }),
  PdfToOffice: dynamic(() => import('./components/PdfToOffice'), { loading, ssr: false }),
  PdfOcr: dynamic(() => import('./components/PdfOcr'), { loading, ssr: false }),
  PdfPageEditor: dynamic(() => import('./components/PdfPageEditor'), { loading, ssr: false }),
  PdfWatermark: dynamic(() => import('./components/PdfWatermark'), { loading, ssr: false }),
  PdfSecurity: dynamic(() => import('./components/PdfSecurity'), { loading, ssr: false }),
  PdfPageNumbers: dynamic(() => import('./components/PdfPageNumbers'), { loading, ssr: false }),
  PdfMetadataTool: dynamic(() => import('./components/PdfMetadataTool'), { loading, ssr: false }),
  PdfRotateTool: dynamic(() => import('./components/PdfRotateTool'), { loading, ssr: false }),
  PdfCompressTool: dynamic(() => import('./components/PdfCompressTool'), { loading, ssr: false }),
  PdfEditor: dynamic(() => import('./components/PdfEditor'), { loading, ssr: false }),

  // Design Tools
  ColorPicker: dynamic(() => import('./components/ColorPicker'), { loading, ssr: false }),
  GradientGenerator: dynamic(() => import('./components/GradientGenerator'), { loading, ssr: false }),
  BoxShadowGenerator: dynamic(() => import('./components/BoxShadowGenerator'), { loading, ssr: false }),
  BorderRadiusGenerator: dynamic(() => import('./components/BorderRadiusGenerator'), { loading, ssr: false }),
  ColorPaletteGenerator: dynamic(() => import('./components/ColorPaletteGenerator'), { loading, ssr: false }),
  ContrastChecker: dynamic(() => import('./components/ContrastChecker'), { loading, ssr: false }),
  FontPreviewTool: dynamic(() => import('./components/FontPreviewTool'), { loading, ssr: false }),

  // Utility Tools
  QrCodeGenerator: dynamic(() => import('./components/QrCodeGenerator'), { loading, ssr: false }),
  QrCodeScanner: dynamic(() => import('./components/QrCodeScanner'), { loading, ssr: false }),
  BarcodeGenerator: dynamic(() => import('./components/BarcodeGenerator'), { loading, ssr: false }),
  BarcodeReader: dynamic(() => import('./components/BarcodeReader'), { loading, ssr: false }),
  RandomNumberGenerator: dynamic(() => import('./components/RandomNumberGenerator'), { loading, ssr: false }),
  DiceRoller: dynamic(() => import('./components/DiceRoller'), { loading, ssr: false }),
  CoinFlip: dynamic(() => import('./components/CoinFlip'), { loading, ssr: false }),
  PasswordGenerator: dynamic(() => import('./components/PasswordGenerator'), { loading, ssr: false }),
  PasswordStrength: dynamic(() => import('./components/PasswordStrength'), { loading, ssr: false }),
  UnitConverter: dynamic(() => import('./components/UnitConverter'), { loading, ssr: false }),
  PercentageCalculator: dynamic(() => import('./components/PercentageCalculator'), { loading, ssr: false }),
  UuidBulkGenerator: dynamic(() => import('./components/UuidBulkGenerator'), { loading, ssr: false }),

  // SEO Tools
  RobotsTxtGenerator: dynamic(() => import('./components/RobotsTxtGenerator'), { loading, ssr: false }),
  MetaTagGenerator: dynamic(() => import('./components/MetaTagGenerator'), { loading, ssr: false }),
  SchemaGenerator: dynamic(() => import('./components/SchemaGenerator'), { loading, ssr: false }),
  OgPreview: dynamic(() => import('./components/OgPreview'), { loading, ssr: false }),
  KeywordDensity: dynamic(() => import('./components/KeywordDensity'), { loading, ssr: false }),
  SerpPreview: dynamic(() => import('./components/SerpPreview'), { loading, ssr: false }),
  MetaExtractor: dynamic(() => import('./components/MetaExtractor'), { loading, ssr: false }),
  HeadingAnalyzer: dynamic(() => import('./components/HeadingAnalyzer'), { loading, ssr: false }),
};
