"use client";

/**
 * SEO Title: Robots.txt Generator - Create SEO-friendly Robots.txt Online
 * Meta Description: Generate valid robots.txt files for your website. Includes presets for Googlebot, GPTBot, ClaudeBot and more. Fast, free, and secure.
 */

import React, { useState, useEffect } from 'react';
import { copyToClipboard, downloadFile } from '@/lib/utils';
import { Bot, Copy, Download, RefreshCw, Plus, Trash2 } from 'lucide-react';

const PRESETS = [
  { name: 'Googlebot', agent: 'Googlebot', allow: '/', disallow: '/admin/' },
  { name: 'GPTBot', agent: 'GPTBot', allow: '', disallow: '/' },
  { name: 'ClaudeBot', agent: 'Claude-Web', allow: '', disallow: '/' },
  { name: 'Common Crawl', agent: 'CCBot', allow: '', disallow: '/' },
];

export default function RobotsTxtGenerator() {
  const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml');
  const [rules, setRules] = useState([
    { agent: '*', allow: '/', disallow: '' }
  ]);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const generate = () => {
    let result = '# Robots.txt generated by ToolifyX\n\n';
    rules.forEach(rule => {
      result += `User-agent: ${rule.agent || '*'}\n`;
      if (rule.allow) result += `Allow: ${rule.allow}\n`;
      if (rule.disallow) result += `Disallow: ${rule.disallow}\n`;
      result += '\n';
    });
    if (sitemap) {
      result += `Sitemap: ${sitemap}\n`;
    }
    setOutput(result.trim());
  };

  useEffect(() => {
    generate();
  }, [sitemap, rules]);

  const addRule = () => {
    setRules([...rules, { agent: '*', allow: '', disallow: '' }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updateRule = (index: number, field: string, value: string) => {
    const newRules = [...rules];
    (newRules[index] as any)[field] = value;
    setRules(newRules);
  };

  const applyPreset = (preset: typeof PRESETS[0]) => {
    setRules([...rules, { agent: preset.agent, allow: preset.allow, disallow: preset.disallow }]);
  };

  return (
    <div className="w-full p-4 md:p-8 space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-7 space-y-6">
           <div className="card border rounded-2xl p-6 bg-card shadow-sm space-y-6">
              <div className="space-y-2">
                 <label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground px-1">Sitemap URL</label>
                 <input
                    type="text"
                    className="w-full border rounded-xl p-3 bg-muted/20 focus:ring-2 focus:ring-primary/20 outline-none font-bold"
                    placeholder="https://example.com/sitemap.xml"
                    value={sitemap}
                    onChange={e => setSitemap(e.target.value)}
                 />
              </div>

              <div className="space-y-4">
                 <div className="flex items-center justify-between">
                    <h3 className="text-xs font-black uppercase tracking-widest text-foreground flex items-center gap-2">
                       <Bot className="w-4 h-4" /> Crawl Rules
                    </h3>
                    <button onClick={addRule} className="text-[10px] font-black text-primary uppercase flex items-center gap-1 hover:underline">
                       <Plus className="w-3 h-3" /> Add Agent
                    </button>
                 </div>

                 <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                    {rules.map((rule, i) => (
                      <div key={i} className="p-4 border rounded-xl bg-muted/5 relative group animate-in slide-in-from-left-2 duration-300">
                         <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                            <div className="space-y-1">
                               <span className="text-[8px] font-black uppercase text-muted-foreground">User-agent</span>
                               <input type="text" value={rule.agent} onChange={e => updateRule(i, 'agent', e.target.value)} className="w-full border rounded-lg p-2 text-xs font-bold bg-background" />
                            </div>
                            <div className="space-y-1">
                               <span className="text-[8px] font-black uppercase text-muted-foreground">Allow</span>
                               <input type="text" value={rule.allow} onChange={e => updateRule(i, 'allow', e.target.value)} className="w-full border rounded-lg p-2 text-xs font-bold bg-background" placeholder="/" />
                            </div>
                            <div className="space-y-1">
                               <span className="text-[8px] font-black uppercase text-muted-foreground">Disallow</span>
                               <input type="text" value={rule.disallow} onChange={e => updateRule(i, 'disallow', e.target.value)} className="w-full border rounded-lg p-2 text-xs font-bold bg-background" placeholder="/admin" />
                            </div>
                         </div>
                         {rules.length > 1 && (
                           <button onClick={() => removeRule(i)} className="absolute -top-2 -right-2 bg-destructive text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-all shadow-lg">
                              <Trash2 className="w-3 h-3" />
                           </button>
                         )}
                      </div>
                    ))}
                 </div>
              </div>
           </div>

           <div className="card border rounded-xl p-6 bg-card shadow-sm space-y-4">
              <h3 className="text-xs font-black uppercase tracking-widest text-muted-foreground">Bot Presets</h3>
              <div className="flex flex-wrap gap-2">
                 {PRESETS.map(p => (
                   <button
                      key={p.name}
                      onClick={() => applyPreset(p)}
                      className="px-3 py-2 rounded-lg border border-border bg-muted/20 text-[10px] font-black uppercase tracking-widest hover:bg-primary hover:text-white transition-all"
                   >
                      Add {p.name}
                   </button>
                 ))}
              </div>
           </div>
        </div>

        <div className="lg:col-span-5 space-y-6">
           <div className="card border rounded-xl bg-card shadow-sm h-full flex flex-col min-h-[400px]">
              <div className="h-12 border-b border-border bg-muted/30 flex items-center px-4 justify-between">
                <span className="text-[10px] font-black uppercase tracking-widest text-primary">Preview Robots.txt</span>
                <div className="flex items-center gap-3">
                   <button onClick={() => { downloadFile(new Blob([output]), 'robots.txt'); }} title="Download robots.txt" className="text-muted-foreground hover:text-foreground">
                      <Download className="w-4 h-4" />
                   </button>
                   <button
                      onClick={async () => { await copyToClipboard(output); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
                      className="text-[10px] font-black text-primary uppercase hover:underline"
                   >
                      {copied ? 'Copied!' : 'Copy'}
                   </button>
                </div>
              </div>
              <textarea
                readOnly
                className="flex-1 p-6 font-mono text-sm bg-transparent outline-none resize-none leading-relaxed text-blue-600 dark:text-blue-400"
                value={output}
              />
           </div>
        </div>
      </div>
    </div>
  );
}
